### ISSUE TITLE
CMS69v5 error in numerator calculation

### ISSUE THREAD

**Issue by onizuka14** [OSEHRA/popHealth#152]
![beforeend](https://user-images.githubusercontent.com/2553722/46178664-219ecd00-c28e-11e8-8fc1-b74df64da26f.png)
![pophealthbefore](https://user-images.githubusercontent.com/2553722/46178669-25325400-c28e-11e8-8f43-500f4c31a3da.png)
As seen in the images attached in the governament site the criteria for numerator is "starts before end of " which translate to <.
But in popHealth we have "Starts Before or During" which translates to <= so in my sample I'm getting wrong results.

**Comment by petercyli** [comment]
This could be a display issue.  Can you verify which bundle you are using, i.e. 2017.0.2?  and I'm presumming that you are using test files generated by Cypress 3.2.3.  I will replicate and confirm your report. 
Thanks.

**Comment by petercyli** [comment]
Yes.  The login screen will show the installed bundle version.  I presumed that you have removed, i.e., dropped, the production database before you install the new bundle.

**Comment by petercyli** [comment]
I just did a check on the pophealth-demo.osehra.org on CMS69.  It looks as if you installed a different bundle, i.e., 2016.  In your picture, the CMS69 is version 5 instead of version 6 for the 2017 bundle.  When I looked at the measure the 2017 bundle, the criteria for the numerator is SBCWE which translates to "Starts Before or Concurrent with End of".  This corresponds to measure criteria as described in the ahrq.gov site.  Please check your system to make sure you are using the correct bundle.

**Comment by onizuka14** [comment]
![2016](https://user-images.githubusercontent.com/2553722/46310471-df2f0600-c595-11e8-9a83-db804683751a.PNG)
![2017](https://user-images.githubusercontent.com/2553722/46310475-e1916000-c595-11e8-96ea-6c07c6a3a821.PNG)
I installed both, as you can see in the pictures for the 2017 (version 6) its right, but for the 2016 (version 5) its wrong

**Comment by petercyli** [comment]
I did check on the 2016 bundle with the CMS69v5 measure.  The display is as you have described.  However, when I proceeded to do the C2 and C3 tests using the Cypress 3.2.3 based on 2016 bundle, popHealth was able to perform the correct calculation and generated the correct CAT3 and CAT1 files to pass the Cypress test.  This may be a Cypress issue since we use the same engine/rules component for calculation.
